config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_environment.d:
    src: config/environment.d
    dst: ~/.config/environment.d
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    chmod: '700'
  f_xserverrc:
    src: xserverrc
    dst: ~/.xserverrc
  f_xsession:
    src: xsession
    dst: ~/.xsession
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_bash_profile:
    src: bash_profile
    dst: ~/.bash_profile
  d_zsh.d:
    src: zsh.d
    dst: ~/.zsh.d
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_zshrc.d:
    src: zshrc.d
    dst: ~/.zshrc.d
profiles:
  lenovo-x270:
    dotfiles:
    - d_nvim
    - d_kitty
    - d_environment.d
    - d_fish
    - f_xserverrc
    - f_xsession
    - f_xinitrc
    - f_bashrc
    - f_bash_profile
    - d_zsh.d
    - f_zshenv
    - f_zshrc
    - d_zshrc.d
