* Fonts
I'm keeping a list of fonts that I like. 

- [[https://opendyslexic.org/][open dyslexic fonts]] 


#+begin_src emacs-lisp
;; added to $DOOMDIR/config.el
(setq doom-font 
    (font-spec 
        :family "OpenDyslexicM Nerd Font Mono"
        :size 24 
        :style "regular"))
#+end_src

* Themes 
Themes for doom emacs and treemacs.

** Doom 
Select theme favorite with index!

#+begin_src emacs-lisp
(setq theme-favorites
    (list

        'doom-snazzy
        'doom-outrun-electric
        'doom-shades-of-purple))
;; which one i want
(setq doom-theme (nth 2 theme-favorites))
#+end_src

** Treemacs
I also wanna use a treemacs theme.

#+begin_src emacs-lisp
(setq doom-themes-treemacs-theme 'doom-colors)
(with-eval-after-load 'doom-themes
  (doom-themes-treemacs-config))
#+end_src

* Package Reconfigure 

Whenever you reconfigure a package, make sure to wrap your config in an
 `after!' block, otherwise Doom's defaults may override your settings. E.g.

 The exceptions to this rule:

   - Setting file/directory variables (like `org-directory')
   - Setting variables which explicitly tell you to set them before their
     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
   - Setting doom variables (which start with 'doom-' or '+').
#+begin_src emacs-lisp
(setq org-directory "~/org")
#+end_src

* Org

** Get Things Done (GTD)
I'm using the [[https://emacs.cafe/emacs/orgmode/gtd/2017/06/30/orgmode-gtd.html][get things done (GTD) workflow]].

*** The GTD inbox
This is where every thought should be collected. We capture the thought with C-c c

#+begin_src emacs-lisp
(setq org-agenda-files '("~/gtd/inbox.org"
                         "~/gtd/gtd.org"
                         "~/gtd/tickler.org"))
#+end_src

#+begin_src emacs-lisp
(setq org-capture-templates '(("t" "Todo [inbox]" entry
                              (file+headline "~/gtd/inbox.org" "Tasks")
                              "* TODO %i%?")
                              ("T" "Tickler" entry
                               (file+headline "~/gtd/tickler.org" "Tickler")
                              "* %i%? \n %U")))
#+end_src

When processing the inbox, refile each actionable entry so long that it belongs to a project.
if need be, setup a new project out of it.

Here are the refile targets:
#+begin_src emacs-lisp
(setq org-refile-targets '(("~/gtd/gtd.org" :maxlevel . 3)
                           ("~/gtd/someday.org" :level . 1)
                           ("~/gtd/tickler.org" :maxlevel . 2)))
#+end_src

*** The projects file
The main file is [["~/gtd/gtd.org"]]  and has all active projects.

**** Tags
Tagging is done on a headline. Tags can be used for
- Regular caregories like :writing or :emacs:
- Tags for people like :daniel:
- GTD contexts like @phys1400, @email, @jarjar

